package demo.stones.objects;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
	/** Unique id will be generated by session and time */
	private String client;
	/** Price to buy */
	private BigDecimal buyPrice;
	/** Price to sell */
	private BigDecimal sellPrice;
	/** Order time */
	private Date time;
	/** time then order was matched */
	private Date matchTime;
	/** Is order matched or not */
	private volatile boolean matched;
	/** Second order */
	private Order matchedOrder;
	
	/** Method can be called by 2 threads at once */
	public synchronized boolean registerMatch() {
		if(matched) return false;
		return matched = true; //Note this is assignment
	}
	
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(client);
		if(matched) {
			if(sellPrice == null) {
				result.append(" bought ");
			} else {
				result.append(" sold ");
			}
		} else {
			if(sellPrice == null) {
				result.append(" buy ");
			} else {
				result.append(" sell ");
			}
		}
		result.append(" a pumpkin ");
		if(matched) {
			if(sellPrice == null) {
				result.append(" from ");
			} else {
				result.append(" to ");
			}
			result.append(matchedOrder.client);
		}
		result.append(" for ");
		if(sellPrice == null) {
			result.append(buyPrice);
		} else {
			result.append(sellPrice);
		}
		result.append("€");
		return result.toString();
	}
	public BigDecimal getPrice() {
		return sellPrice == null ? buyPrice : sellPrice;
	}
	public Order() {
		
	}
	public Order(String client) {
		this.client = client;
		this.time = new Date();
	}
	
	public String getClient() {
		return client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public BigDecimal getBuyPrice() {
		return buyPrice;
	}

	public void setBuyPrice(BigDecimal buyPrice) {
		this.buyPrice = buyPrice;
	}

	public BigDecimal getSellPrice() {
		return sellPrice;
	}

	public void setSellPrice(BigDecimal sellPrice) {
		this.sellPrice = sellPrice;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Date getMatchTime() {
		return matchTime;
	}

	public void setMatchTime(Date matchTime) {
		this.matchTime = matchTime;
	}

	public boolean isMatched() {
		return matched;
	}

	public void setMatched(boolean matched) {
		this.matched = matched;
	}

	public Order getMatchedOrder() {
		return matchedOrder;
	}

	public void setMatchedOrder(Order matchedOrder) {
		this.matchedOrder = matchedOrder;
	}

}
